import { IEntityAddress } from "./entityAddress";
import { IPhoto } from "./photo";
import { IUserAttachment } from "./userAttachment";
import { IUserExp } from "./userExp";
import { IUserPassport } from "./userPassport";
import { IUserPhone } from "./userPhone";
import { IUserProfession } from "./userProfession";
import { IUserQualification } from "./userQualification";

export interface ICandidate {
     //checked: boolean;
     id: number;
     userType: string;
     applicationNo: number;
     gender: string;
     firstName: string;
     secondName: string;
     familyName: string;
     knownAs: string;
     referredBy: number;
     referredByName: string;
     dOB: Date;
     placeOfBirth: string;
     aadharNo: string;
     ppNo: string;
     ecnr: boolean;
     city: string;
     pin: string;
     nationality: string;
     email: string;
     companyId: number;
     created: Date;
     introduction: string;
     interests: string;
     appUserIdNotEnforced: string;
     appUserId: number;
     notificationDesired: boolean;
     candidateStatus?: number;     //EnumCnadidateStatus.NotReferred;
     photoUrl?: string;
     lastActive?: Date;
     userPhones: IUserPhone[];
     userQualifications: IUserQualification[];
     userProfessions: IUserProfession[];
     userPassports: IUserPassport[];
     userAttachments: IUserAttachment[];
     entityAddresses: IEntityAddress[];
     userExperiences: IUserExp[];
     userPhotos: IPhoto[];
     //userFormFiles: File[];
}